### ISSUE TITLE
Cannot save view: Returned attributes must not be changed

### ISSUE THREAD

**Issue by bryce2071** [Cinteros/FetchXMLBuilder#74] opened 2015-07-23 15:09 UTC
Hi, 
i tried, saving a generated fetchXML-View to an existing (personal) view, but became the above error.
But, the existing view can not be the same (attributes must not be changed) cause it is a completely other view.
Maybe i cant save views, that cant be done with out-of-the-box customizations of crm ...
cause i did a link-entity in an link-entity to get data and this isnt possible in crm otb?

THX.
Greets PeB

**Comment by bryce2071** [comment] 2015-07-24 13:37
anyone?

**Comment by shytikov** [comment] 2015-07-24 13:50
Let me take a look on this. I will try to reproduce this error locally...

**Comment by shytikov** [comment] 2015-07-24 15:47
@bryce2071 Can you share FetchXML that causes the issue?

Maybe you have attributes with the same name in both tables, and it's vague somehow, which one should be used?

**Comment by shytikov** [comment] 2015-07-28 09:00
Hi @bryce2071, is there any updates? Can you share FetchXML that causes issue, so I can continue my investigation.

Thank you so much in advance!

**Comment by bryce2071** [comment] 2015-07-28 09:39
Hi Alexey, 

 

sorry, i am a bit in toooo much work, sorry sorry .. 

but i have an info/question before sending the fetchXML-Code.

 

Info/Question:

I choosed an existing custom-view of the entity „opportunity“ to update with the new (below) fetch-XML. 

Will that work – or which is the xxxx to use the „update existing view?

Can i use any system- or Custom-View oft he entity „opportunity“?

Or can i create a new view in the 

 

 

fetschXML of existing view:

<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false" >

  <entity name="opportunity" >

    <attribute name="statecode" />

    <attribute name="name" />

    <attribute name="customerid" />

    <attribute name="bd_verkaufschance_typ" />

    <attribute name="bd_firstname" />

    <attribute name="bd_address1_postalcode" />

    <attribute name="bd_address1_city" />

    <attribute name="bd_lastname" />

    <attribute name="bd_med_risikopruefung_gewuenscht" />

    <attribute name="bd_krankenversicherungsstatus" />

    <attribute name="bd_buz_gewuenscht" />

    <attribute name="bd_anfrage_inkl_gesundheitsfragen" />

    <attribute name="opportunityid" />

    <order attribute="bd_verkaufschance_typ" descending="false" />

    <order attribute="name" descending="true" />

    <filter type="and" >

      <filter type="or" >

        <condition attribute="statecode" operator="eq" value="0" />

        <filter type="and" >

          <condition attribute="actualclosedate" operator="last-x-months" value="12" />

          <condition attribute="statecode" operator="eq" value="1" />

        </filter>

      </filter>

      <condition attribute="bd_verkaufschance_typ" operator="not-in" >

        <value>100000025</value>

        <value>100000027</value>

        <value>100000028</value>

        <value>100000026</value>

        <value>100000029</value>

      </condition>

    </filter>

  </entity>

</fetch>

 

<fetch>

  <entity name="opportunity">

    <attribute name="bd_firstname" />

    <attribute name="bd_verkaufschance_typ" />

    <attribute name="name" />

    <attribute name="bd_risikoanschrift" />

    <attribute name="bd_name" />

    <attribute name="bd_lastname" />

    <attribute name="bd_address1_line1" />

    <attribute name="bd_address1_postalcode" />

    <attribute name="bd_agenturnummerid" />

    <attribute name="bd_address1_city" />

    <attribute name="statecode" />

    <attribute name="bd_salutation" />

    <attribute name="accountidname" />

    <filter type="and">

      <condition attribute="bd_verkaufschance_typ" operator="eq" value="100000014" />

    </filter>

    <link-entity name="bd_agenturnummer" from="bd_agenturnummerid" to="bd_agenturnummerid" alias="agnr" visible="true">

      <link-entity name="contact" from="contactid" to="bd_vermittler_kid" alias="vm" visible="true">

        <attribute name="bd_epost" />

        <attribute name="emailaddress3" />

        <attribute name="emailaddress2" />

        <attribute name="emailaddress1" />

        <attribute name="bd_de_mail" />

      </link-entity>

    </link-entity>

  </entity>

</fetch>

 

Von: Alexey Shytikov [mailto:notifications@github.com] 
Gesendet: Dienstag, 28. Juli 2015 11:00
An: Cinteros/FetchXMLBuilder <FetchXMLBuilder@noreply.github.com>
Cc: bryce <bryce2071@gmail.com>
Betreff: Re: [FetchXMLBuilder] Cannot save view: Returned attributes must not be changed (#74)

 

Hi @bryce2071 <https://github.com/bryce2071> , is there any updates? Can you share FetchXML that causes issue, so I can continue my investigation.

Thank you so much in advance!

**Comment by bryce2071** [comment] 2015-07-28 09:58
Hi Alexey, 

 

sorry, i am a bit in toooo much work, sorry sorry .. 

but i have an info/question before sending the fetchXML-Code.

 

Info/Question:

 

I choosed a custom-view of the entity „opportunity“ to update with the new (below) fetch-XML. 

Will that work – or which is the requirement to use the „update existing view?

Can i use any system- or Custom-View of the entity „opportunity“?

Maybe the error is, that i open an view, pasting the new fetchXML into (with „Exit XML“) and then saving the view?

Or can i create a new view in XrmToolBox and write it to crm?

 

fetchXML of Opend custom view :

 

<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false" >

  <entity name="opportunity" >

    <attribute name="statecode" />

    <attribute name="name" />

    <attribute name="customerid" />

    <attribute name="bd_verkaufschance_typ" />

    <attribute name="bd_firstname" />

    <attribute name="bd_address1_postalcode" />

    <attribute name="bd_address1_city" />

    <attribute name="bd_lastname" />

    <attribute name="bd_med_risikopruefung_gewuenscht" />

    <attribute name="bd_krankenversicherungsstatus" />

    <attribute name="bd_buz_gewuenscht" />

    <attribute name="bd_anfrage_inkl_gesundheitsfragen" />

    <attribute name="opportunityid" />

    <order attribute="bd_verkaufschance_typ" descending="false" />

    <order attribute="name" descending="true" />

    <filter type="and" >

      <filter type="or" >

        <condition attribute="statecode" operator="eq" value="0" />

        <filter type="and" >

          <condition attribute="actualclosedate" operator="last-x-months" value="12" />

          <condition attribute="statecode" operator="eq" value="1" />

        </filter>

      </filter>

      <condition attribute="bd_verkaufschance_typ" operator="not-in" >

        <value>100000025</value>

        <value>100000027</value>

        <value>100000028</value>

        <value>100000026</value>

        <value>100000029</value>

      </condition>

    </filter>

  </entity>

</fetch>

 

 

fetchXML pasted into the existing custom view  (by clicking „Edit XML“ and pasting the custom code in):

 

<fetch>

  <entity name="opportunity">

    <attribute name="bd_firstname" />

    <attribute name="bd_verkaufschance_typ" />

    <attribute name="name" />

    <attribute name="bd_risikoanschrift" />

    <attribute name="bd_name" />

    <attribute name="bd_lastname" />

    <attribute name="bd_address1_line1" />

    <attribute name="bd_address1_postalcode" />

    <attribute name="bd_agenturnummerid" />

    <attribute name="bd_address1_city" />

    <attribute name="statecode" />

    <attribute name="bd_salutation" />

    <attribute name="accountidname" />

    <filter type="and">

      <condition attribute="bd_verkaufschance_typ" operator="eq" value="100000014" />

    </filter>

    <link-entity name="bd_agenturnummer" from="bd_agenturnummerid" to="bd_agenturnummerid" alias="agnr" visible="true">

      <link-entity name="contact" from="contactid" to="bd_vermittler_kid" alias="vm" visible="true">

        <attribute name="bd_epost" />

        <attribute name="emailaddress3" />

        <attribute name="emailaddress2" />

        <attribute name="emailaddress1" />

        <attribute name="bd_de_mail" />

      </link-entity>

    </link-entity>

  </entity>

</fetch>

 

 

Von: Alexey Shytikov [mailto:notifications@github.com] 
Gesendet: Dienstag, 28. Juli 2015 11:00
An: Cinteros/FetchXMLBuilder <FetchXMLBuilder@noreply.github.com>
Cc: bryce <bryce2071@gmail.com>
Betreff: Re: [FetchXMLBuilder] Cannot save view: Returned attributes must not be changed (#74)

 

Hi @bryce2071 <https://github.com/bryce2071> , is there any updates? Can you share FetchXML that causes issue, so I can continue my investigation.

Thank you so much in advance!

**Comment by shytikov** [comment] 2015-07-28 11:11
That's ok! Thank you for information! Working on it!

**Comment by shytikov** [comment] 2015-07-29 07:14
@bryce2071 One more favor, can you fully copy error message (it should contain list of attributes)?

It could be simply done by pressing <kbd>Ctrl+C</kbd> on focused error message. Or if it's easier for you, may you just post screenshot for the error message?

Thank you in advance!

**Comment by bryce2071** [comment] 2015-07-29 07:31
there it is 

 

---------------------------

Cannot save view

---------------------------

Cannot save view, returned attributes must not be changed.

 

Expected attributes:

  statecode

 name

  customerid

  bd_dst

  bd_firstname

  bd_address1_postalcode

  bd_address1_city

  bd_lastname

  bd_med_rp

  bd_kvstat

  bd_buz

  bd_anfr_incl_ghfr

  opportunityid

  

Current attributes:

  bd_firstname

  bd_dst

  name

  bd_radr

  bd_name

  bd_lastname

  bd_address1_line1

  bd_address1_postalcode

  bd_agnrid

  bd_address1_city

  statecode

  bd_salutation

  accountidname

  vm.bd_epost

  vm.emailaddress3

  vm.emailaddress2

  vm.emailaddress1

  vm.bd_de_mail

  

---------------------------

OK   

---------------------------

**Comment by shytikov** [comment] 2015-07-29 08:56
@bryce2071, I've consulted with @rappen about this issue, the way how you're trying to use `FXB` is not currently supported. Currently implemented view handling features are following:  
* Open existing
* Update IF attributes are the same as when opened (change the criteria etc, introduce outer joins, not-in etc.)

The reason why adding and removing attributes are not supported yet is the LayoutXML that stored in `userquery`. It is possible to modify FetchXML in the way that LayoutXML will fail (for example referencing none-existing attributes).

I will start new development with following features:
* Allow adding new attributes to FetchXML for `userquery`;
* Implement ability to edit LayoutXML taking into account underlying FetchXML;
* This will enable us to create new custom views from `FXB`.

This will be separate branch, unstable, but you will be able to run these builds to complete tasks you're working with.

**Comment by bryce2071** [comment] 2015-07-29 09:31
Hi Alexey,

hey this sounds great.
many many thx for developing my needs.

I am really excited for that.

Because i am not very familar with github.
Where / when can i download this branch?

THX,
Greets Peter

Gruss
Peter Bohn

bryce2071@gmail.com

Tel: 07221/ 80 36 16
Fax: 07221 8035593
Mobil: 0172/ 261 90 76

2015-07-29 10:56 GMT+02:00 Alexey Shytikov <notifications@github.com>:

**Comment by bryce2071** [comment] 2015-07-29 09:40
Hi Alexey,

 

hey this sounds great. 

many many thx for developing my needs.




Gruss
Peter Bohn

bryce2071@gmail.com <mailto:bryce2071@gmail.com> 

Tel: 07221/ 80 36 16
Fax: 07221 8035593
Mobil: 0172/ 261 90 76

 

2015-07-29 10:56 GMT+02:00 Alexey Shytikov <notifications@github.com <mailto:notifications@github.com> >:

@bryce2071 <https://github.com/bryce2071> , I've consulted with @rappen <https://github.com/rappen>  about this issue, the way how you're trying to use FXB is not currently supported. Currently implemented view handling features are following: 

*	Open existing
*	Update IF attributes are the same as when opened (change the criteria etc, introduce outer joins, not-in etc.)

The reason why adding and removing attributes are not supported yet is the LayoutXML that stored in userquery. It is possible to modify FetchXML in the way that LayoutXML will fail (for example referencing none-existing attributes).

I will start new development with following features:

*	Allow adding new attributes to FetchXML for userquery;
*	Implement ability to edit LayoutXML taking into account underlying FetchXML;
*	This will enable us to create new custom views from FXB.

This will be separate branch, unstable, but you will be able to run these builds to complete tasks you're working with.

**Comment by bryce2071** [comment] 2015-08-04 19:20
Hi again, 

i don't know how to find the solution, you are working on?
Sorry, but can you post a direkt link?

THX, Greets Peb

**Comment by shytikov** [comment] 2015-08-05 06:51
Hi Peb,

I'm working on it! Need a bit more time to complete, but I will post direct link here, ASAP.

**Comment by bryce2071** [comment] 2015-08-05 07:02
thx, great.

 

Geets PeB

**Comment by rappen** [comment] 2015-08-11 06:38
Closing this as the solution will be part of another XTB plugin, soon to be released.

**Closed by rappen** 2015-08-11 06:38 UTC
Labels: enhancement

**Comment by shytikov** [comment] 2015-08-13 13:42
@bryce2071 I've developed plugin to design views.

Please take a look on binary attached to following release: https://github.com/Cinteros/XrmToolBox.Plugins/releases/tag/view-designer-preview1

Just unblock archive and unzip contents of the file to `Plugins` folder of your `XrmToolBox` installation and restart `XTB`.

You will see new plugins. And `View Designer` is what you need.

It will allow you do the most of operations you would love to do with view. Some functionality still might be missing, I'm working on it.

If you will find bugs, please share this information with me, I would be glad to quickly fix them.

**Comment by bryce2071** [comment] 2015-08-13 16:01
Hey Alexey, 

 

looks very nice and sounds like this is exactely what i need.

 

how to remove htis?



 

 

greetings PeB

 

@bryce2071 <https://github.com/bryce2071>  I've developed plugin to design views.

Please take a look on binary attached to following release: https://github.com/Cinteros/XrmToolBox.Plugins/releases/tag/view-designer-preview1

Just unblock archive and unzip contents of the file to Plugins folder of your XrmToolBox installation and restart XTB.

You will see new plugins. And View Designer is what you need.

It will allow you do the most of operations you would love to do with view. Some functionality still might be missing, I'm working on it.

If you will find bugs, please share this information with me, I would be glad to quickly fix them.

**Comment by bryce2071** [comment] 2015-08-13 16:07
sorry, ist working now.

dont know why.

 

--

gr. PeB

 

 

 

@bryce2071 <https://github.com/bryce2071>  I've developed plugin to design views.

Please take a look on binary attached to following release: https://github.com/Cinteros/XrmToolBox.Plugins/releases/tag/view-designer-preview1

Just unblock archive and unzip contents of the file to Plugins folder of your XrmToolBox installation and restart XTB.

You will see new plugins. And View Designer is what you need.

It will allow you do the most of operations you would love to do with view. Some functionality still might be missing, I'm working on it.

If you will find bugs, please share this information with me, I would be glad to quickly fix them.
